name: Inform .github repository ℹ️

on:
  push:
    branches:
      - 'main'
      - 'master'
      - 'develop'
      - 'feature/**'

jobs:
  dispacher:
    runs-on: ubuntu-latest
    name: webservices
    steps:
      - name: repository-dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: tudat-team/.github
          event-type: inform
          client-payload: >-
            {
            "event": "${{ github.event }",
            "actor": "${{ github.actor }}",
            "repository": "${{ github.repository }}",
            "ref": "${{ github.ref }}"
            }
